// Single source of truth for role→domain mapping
// Removed roles: POWERPLANT_OPERATOR, RECYCLING_COORDINATOR, WATER_TREATMENT_MEMBER

const ROLE_TO_DOMAIN = {
  ENERGY_TECHNICIAN: 'ELECTRICITY', NMC_MEMBER: 'ELECTRICITY',
  PLUMBING_SPECIALIST: 'WATER',     IRRIGATION_MANAGER: 'WATER',
  WASTE_MANAGER: 'WASTE',           SANITATION_OFFICER: 'WASTE',
};

const DOMAIN_ASSIGNEE = {
  ELECTRICITY: 'ENERGY_TECHNICIAN',
  WATER:       'PLUMBING_SPECIALIST',
  WASTE:       'SANITATION_OFFICER',
};

// Field roles: only see tickets assigned directly to them
const FIELD_ROLES = ['ENERGY_TECHNICIAN', 'PLUMBING_SPECIALIST', 'SANITATION_OFFICER'];

// Strategic roles: see all tickets in their domain
const STRATEGIC_ROLES = ['OFFICER', 'NMC_MEMBER', 'IRRIGATION_MANAGER', 'WASTE_MANAGER'];

module.exports = { ROLE_TO_DOMAIN, DOMAIN_ASSIGNEE, FIELD_ROLES, STRATEGIC_ROLES };
