// Removed: POWERPLANT_OPERATOR, RECYCLING_COORDINATOR, WATER_TREATMENT_MEMBER
export const UserRole = {
  OFFICER:             'OFFICER',
  ENERGY_TECHNICIAN:   'ENERGY_TECHNICIAN',
  NMC_MEMBER:          'NMC_MEMBER',
  PLUMBING_SPECIALIST: 'PLUMBING_SPECIALIST',
  IRRIGATION_MANAGER:  'IRRIGATION_MANAGER',
  WASTE_MANAGER:       'WASTE_MANAGER',
  SANITATION_OFFICER:  'SANITATION_OFFICER',
};

export const ResourceType = {
  ELECTRICITY: 'ELECTRICITY',
  WATER:       'WATER',
  WASTE:       'WASTE',
};
